name: Welcome New Contributor

on:
  pull_request:
    types: [opened]

permissions:
  pull-requests: write
  contents: write

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Greet first-time contributor
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Thanks for opening your first issue! 🎉"
          pr-message: "Thanks for your first pull request! 🚀 We're excited to have you contribute."
